### ISSUE TITLE
Hey?

### ISSUE THREAD

**Issue by xZeroMCPE** [CaptainDuck/MCPE-Installers#2]
BukkitPE has been released and i was wanting a installation script instead that downloads jars for them..ect) Is it okay if i use your script and add a bit of more stuff? or are you okay doing it for us?? 

Here is our project: www.GitHub.com/BukkitPE/BukkitPE

**Comment by CaptainDuck** [comment]
Okay, wait.. But is there a tutorial to install? Or is it just like Nukkt becoz its written in Java xD

**Comment by xZeroMCPE** [comment]
@CaptainDuck  There isn't a  tutorial to install to install but running it is easy as running a java file.

As long they have the jar file/download it from our jenkins they can start it using these scipt
Start.cmd for windows
https://github.com/BukkitPE/BukkitPE/blob/master/start.cmd

for linux base system

https://github.com/BukkitPE/BukkitPE/blob/master/start.sh

Just take a look at it. It's easy to install it/start it

**Comment by xZeroMCPE** [comment]
If you need us visit our forums. Forums.BukkitPE.net

**Comment by CaptainDuck** [comment]
Is there a difference between Nukkit and BukkitPE? im seeing some sources..

**Comment by xZeroMCPE** [comment]
@CaptainDuck  Support pc Bukkit /spigot plugins

**Comment by CaptainDuck** [comment]
Rly? Have u tested it?
